apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermarket
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermarket
  template:
    metadata:
      labels:
        app: supermarket
        version: v1
    spec:
        containers:
        - name: supermarket-api
          command: [
            "api",
            "--handler=rpc",
            "--address=:8080",
            "--namespace=supermarket"
          ]
          image: microhq/micro
          ports:
          - containerPort: 8080