version: '3.1'

services:
  discount-api:
    build: ../supermarket.discount.api
    ports:
      - 50052:50052
    environment: 
      MICRO_SERVER_ADDRESS: ":50052"

  product-api:
    build: ../supermarket.products.api
    ports:
      - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      CORS_ALLOWED_HEADERS: "X-Custom-Header"
      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: "POST"
  
  gateway-api:
    image: microhq/micro
    command: api --handler=rpc --address=:8080 --namespace=supermarket
    ports:
      - 8080:8080
    environment:
      - MICRO_REGISTRY=mdns 
    

